name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Prepare WWW Folder
        run: |
          mkdir www
          cp *.html *.js *.css *.json www/ || true

      - name: Prepare Capacitor
        run: |
          npx cap add android

      - name: Build Android App Bundle
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ArsivX-Android-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
